export const USER_ACTION_TYPES = {
	SET_USERS: 'SET_USERS',
	SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
	SET_META: 'SET_META',
	SET_SEARCH_TERM: 'SET_SEARCH_TERM',
	SET_DELETED_USERS: 'SET_DELETED_USERS',
	SET_UPDATED_USERS: 'SET_UPDATED_USERS',
	SET_NEW_USERS: 'SET_NEW_USERS',
};
